config/routes.rb
Rails.application.routes.draw do
  resources :books do
  	resources :posts, shallow: true
    resources :articles
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :book
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :articles, inverse_of: :book
	has_many :posts, inverse_of: :book
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:new, :create, :show, :index, :edit]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    #byebug
    @article = @book.articles.build
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = @book.articles.build(article_params)
    respond_to do |format|
      if @article.save
        format.html { redirect_to book_article_path(@article.book, @article), notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to book_article_path(@article.book, @article), notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_book
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :desc)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

before_action :set_book, only: [:show]

def index
	@books =  Book.all
end

def new
	@book = Book.new
end
def create
	@book = Book.create(book_params)
	@book.save

	respond_to do |format|
		format.html { redirect_to @book }
	end
end

def show
end

private

def book_params
	params.require(:book).permit(:title, :desc)
end

def set_book
	@book = Book.find(params[:id])
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_book, only: [:new, :create, :index, :edit]


  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = @book.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @book.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end


    def set_book
      @book = Book.find(params[:book_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :desc, :book_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/articles/_form.html.erb
<%= form_for([book, article]) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.label :desc %></p>
  <p><%= f.text_field :desc %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= form_for([@book, @article], url: book_article_path(@book, @article)) do |f| %>


    <p><%= f.label :title %></p>
  <p><%= f.text_field :title %></p>
  <p><%= f.label :desc %></p>
  <p><%= f.text_field :desc %></p>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Show', book_article_path(@article.book, @article) %> |
<%= link_to 'Back', book_articles_path(@book, @article) %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.desc %></td>
        <td><%= link_to 'Show', book_article_path(article.book,article) %></td>
        <td><%= link_to 'Edit', edit_book_article_path(article.book, article) %></td>
        <td><%= link_to 'Destroy', book_article_path(article.book,article), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_book_article_path(@book) %> | 
<%= link_to 'Back', book_path(@book) %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article, book: @book %>

<%= link_to 'Back', book_articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

  <p><%= @article.title %></p>
  <p><%= @article.desc %></p>

<%= link_to 'Edit', edit_book_article_path(@book, @article) %> |
<%= link_to 'Back', book_articles_path(@book) %>

app/views/books/index.html.erb
<h1>Books#index</h1>
<% @books.each do |book|%>
<p><%=  book.title %></p>
<p><%=  book.desc %></p>

	<% book.articles.each do |article|%>
		<p><%=  article.title %></p>
		<p><%=  article.desc %></p>

		<p>----   end  of article ------------</p>
	<% end %>
		<%= link_to 'Create Article', new_book_article_path(book.id) %>

	<% book.posts.each do |post|%>
		<p><%=  post.title %></p>
		<p><%=  post.desc %></p>

		<p>----   end  of post ------------</p>
	<% end %>
		<%= link_to 'Create post', new_book_post_path(@book.id) %>


<p>---- end of books -----------</p>
<% end %>


<%= link_to 'Create book', new_book_path %>

app/views/books/new.html.erb
<%=  form_for @book  do |f| %>
	<p><%= f.label :title %></p>
	<p><%= f.text_field :title %></p>
	<p><%= f.label :desc %></p>
	<p><%= f.text_field :desc %></p>
	<%= f.submit 'create book' %>

<% end %>

app/views/books/show.html.erb
<h3><%=  @book.title %></h3>
<h4><%=  @book.desc %></h4>

<% @book.articles.each do |article|%>
		<p><%=  article.title %></p>
		<p><%=  article.desc %></p>
		<%= link_to 'Show', book_article_path(article.book,article) %>
		<p>----   end  of article ------------</p>
	<% end %>
		<%= link_to 'Create Article', new_book_article_path(@book.id) %>


			<% @book.posts.each do |post|%>
		<p><%=  post.title %></p>
		<p><%=  post.desc %></p>

		<p>----   end  of post ------------</p>
	<% end %>
		<%= link_to 'Create post', new_book_post_path(@book.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Library</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for([book, post]) do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :book_id %>
    <%= f.text_field :book_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Desc</th>
      <th>Book</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.desc %></td>
        <td><%= post.book.title %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_book_post_path(@book.id) %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, book: @book %>

<%= link_to 'Back', post_path(@book) %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Desc:</strong>
  <%= @post.desc %>
</p>

<p>
  <strong>Book:</strong>
  <%= @post.book.title %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', post_path %>